region = "us-east-2"
runtime = "nodejs12.x"
timeout = "900"
handler_name = "JS/write_to_dynamodb"
handler_name_create = "JS/create"
handler_name_read = "JS/read"
handler_name_update = "JS/update"
handler_name_delete = "JS/delete"